name: Build/release

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Python.
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: |
          sudo apt update
          sudo apt install ffmpeg
          pip install moviepy pydub vosk tqdm nnsplit
      - name: Run unit tests.
        run: |
          python -m unittest
      
      - name: Install build tools and generate distribution archives.
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Publish a Python distribution to PyPI.
        uses: pypa/gh-action-pypi-publish@master
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: __token__
          # Config for secret: pypi_password.
          password: ${{ secrets.pypi_password }}
